# Page settings

baseurl = "https://cv.boyouz.com/"
languageCode = "en-us"
title = "Boyou Zhou Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-121966599-1"
publishDir = "docs"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Boyou Zhou"
        tagline = "Software Developement Engineer"
        avatar = "avatar.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: bobzhou@bu.edu"
        title = "bobzhou@bu.edu"

        [[params.contact.list]]
        class = "google"
        icon = "fa-google"
        url = "//scholar.google.com/citations?user=J_zkbygAAAAJ&hl=en"
        title = "google-scholar"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//cv.boyouz.com"
        title = "cv.boyouz.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/boyou-zhou-87272480"
        title = "linkedin.com/in/boyou-zhou-87272480"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/byzhou"
        title = "github.com/byzhou"

        [[params.contact.list]]
        class = "gpg bobzhou@bu.edu"
        icon = "fa-lock"
        url = "https://flowcrypt.com/pub/bobzhou@bu.edu"
        title = "GPG: CC43 E037 BDC3 9946 327A 2D61 920A 748C B7A9 9302"

        [[params.contact.list]]
        class = "gpg bobzhouboyou@gmail.com"
        icon = "fa-lock"
        url = "https://flowcrypt.com/pub/bobzhouboyou@gmail.com"
        title = "GPG: 8177 0C6E C220 984F 5AF4 779F 346F 185E DB1E 4F4B"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "PhD in Computer Engineering"
        college = "Boston University"
        dates = "2013 - 2019"

        [[params.education.list]]
        degree = "BSc in Communication Engineering"
        college = "Southeast University"
        dates = "2009 - 2013"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Hiking"

        [[params.interests.list]]
        interest = "Swimming"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "A research pioneer in Computer Engineering with multiple research papers and commercial interests. Highly motivated and data oriented professional with technical, people and communication skills required to be a valuable asset to any team pursuing solutions in embedded software and security."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Software Developement Engineer"
        dates = "2020 - present"
        company = "Amazon.com Inc."
        details = "Java/Android Development: Android development, Java Server Development"

        [[params.jobs.list]]
        position = "Embedded System and Software Engineer"
        dates = "2019 - 2020"
        company = "Analog Devices Inc."
        details = "Embedded Software Development: C/C++ Embedded Development, Server Development, Python/Network/RabbitMQ Development"

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "2013 - 2019"
        company = "Boston University"
        details = "Software/Hardware System Security Research: Malware Analysis, Hardware Trojan Detection, Encryption Acceleration"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**My past projects and related publications** During my graduate school, I have worked on a variety of projects related to computer system security design. Below is the listed work and publications."

        [[params.projects.list]]
        title = "Hardware Performance Counter Malware Detection "
        url = "https://github.com/bu-icsg/Hardware_Performance_Counters_Can_Detect_Malware_Myth_or_Fact"
        tagline = "**BEST PAPER in AsiaCCS 2018** By literature survey, I found prevalent unrealistic assumptions and misconducts in Hardware Performance Counters (HPCs) malware detection using machine learning. To re-evaluate the feasibility of malware detection using Hardware Performance Counters (HPC), I measured the HPC traces on various programs, including 1,000 malware and 1,000 benignware. To perform the measurements, I used Rabbitmq to orchestra the communications in a cluster of machines.  During the experiments, I modified the GRUB boot loader to reset the disk image after every malware experiment. I performed data analysis on these HPC values using various machine learning algorithms, such as K Nearest Neighbors (KNN), Decision Tree (DT), Multilayer Perceptrons (MLP), Naive Bayes, AdaBoost and Random Forest (RF). By applying these machine learning algorithms, I evaluated the robustness of malware detection using cross-validations."

        [[params.projects.list]]
        title = "Hardware Trojan Detection Through Near-IR Imaging"
        url = "https://ieeexplore.ieee.org/abstract/document/9082689/"
        pdf = "guest_talk.pdf"
        tagline = "Hardware Trojans (HT) are maliciously-inserted hardware blocks in Integrated Circuits (IC). Traditional testing/validation techniques, for example, power and timing validation methods, are not able to detect HTs. Our group collaborated with optical imaging group to develop optical-backside imaging. I worked as the support for the IC design, data-processing in this project. I engineered optical structures in standard cells, and designed hardware watermarks in the ICs to detect any modifications made by the intruders. After designing the optical structures, I used various data processing, such as correlations, noise analysis, and machine learning, to elevate the HT detection accuracies. With these engineered structures, we can perform classications between dierent kinds of standard cells, such that any modifications or replacement to these cells can be easily detected through optical imaging."


        [[params.projects.list]]
        title = "Hardware Assisted Encryption Acceleration"
        url = "https://ieeexplore.ieee.org/abstract/document/8091062"
        tagline = "To decrease the power consumption and accelerate computations on the Internet of Things (IoT) devices, I worked on the FPGA-assisted cryptographic accelerations. In this project, I used Zedboard as the reconfigurable substrate evaluation platform. The implemented cryptographic algorithms included symmetric cryptography, asymmetric cryptography, and secure hash functions. I also integrated our cryptographic engines with the OpenSSL library to inherit the library's support for block cipher modes. At the same time, the FPGA implementation of cryptographic operations was more exible compared to custom hardware implementations of cryptographic components."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Java"
        level = "93%"

        [[params.skills.list]]
        skill = "C/C++"
        level = "90%"

        [[params.skills.list]]
        skill = "HTML & JAVASCRIPT & CSS"
        level = "75%"

        [[params.skills.list]]
        skill = "Bash & Perl & Any Other Scripting"
        level = "65%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Boyou Zhou"
